# -*- coding: utf-8 -*-
"""ProjectPertama_predictiveAnalytic(A548YBM523) (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GVIg4lioHsMq_R0P0AFrEkO2dzvJ3YXM

# Data Loading
"""

!pip install Sastrawi

"""**Insight**: Memuat pustaka yang diperlukan untuk analisis data, visualisasi, dan pemrosesan teks, termasuk Sastrawi untuk stemming dan stopwords dalam bahasa Indonesia."""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# %matplotlib inline
import seaborn as sns
import os
import shutil
import re
import string
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

from google.colab import files
files.upload()  # upload kaggle.json kamu

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

"""**ingsight**: mengautentikasi akses ke Kaggle API, untuk mengunduh dataset atau mengakses fitur Kaggle langsung dari Colab."""

# Download kaggle dataset and unzip the file
# !cp kaggle.json ~/.kaggle/

# !chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d muhammadghazimuharam/indonesiafalsenews
!unzip indonesiafalsenews.zip

"""**Insight**: Download dataset berita hoax indonesia dari kaggle"""

# Baca file CSV
train_df = pd.read_csv('/content/Data_latih.csv')
test_df = pd.read_csv('/content/Data_uji.csv')

# Gabungkan train dan test
combined_df = pd.concat([train_df, test_df], ignore_index=True)

"""**Insight**: Menggabungkan dataset train dan test"""

# Lihat hasil
print(combined_df.shape)
combined_df.head()

"""**Insight**: Menggabungkan dataset train dan test untuk analisis awal yang lebih menyeluruh.

# Exploratory Data Analysis
"""

combined_df.info()

"""**Insight**: Memeriksa keberadaan missing value dan menghapus baris dengan label yang hilang untuk memastikan kualitas data."""

combined_df.describe()

"""### Melihat Missing Value"""

combined_df.isnull().sum()

combined_df[combined_df['label'].isnull()]

combined_df = combined_df.dropna(subset=['label'])

jumlah_hoax = combined_df[combined_df['label'] == 1].shape[0]
jumlah_benar = combined_df[combined_df['label'] == 0].shape[0]

print("Jumlah Berita Hoax (label 1):", jumlah_hoax)
print("Jumlah Berita Benar (label 0):", jumlah_benar)

"""### Distribusi Label"""

sns.countplot(x='label', data=combined_df)
plt.title('Distribusi Label: Hoax vs Benar')
plt.xticks([0, 1], ['Benar', 'Hoax'])
plt.show()

"""**Insight**: Memvisualisasikan distribusi label untuk melihat apakah dataset seimbang antara berita hoax dan benar.

### Panjang Teks (judul + narasi)
"""

combined_df['text_length'] = combined_df['judul'].str.len() + combined_df['narasi'].str.len()
sns.histplot(data=combined_df, x='text_length', hue='label', bins=50, kde=True)
plt.title('Distribusi Panjang Teks per Label')
plt.show()

"""**Insight**: Menganalisis panjang teks untuk melihat apakah ada pola tertentu antara panjang teks dan label (hoax/benar).

# Data Preprocessing
"""

indofakenews_df = combined_df
indofakenews_df.shape

indofakenews_df['teks'] = indofakenews_df['judul'] + ' ' + indofakenews_df['narasi']

indofakenews_df = indofakenews_df[['teks', 'label']]

"""**Insight**: Menggabungkan kolom judul dan narasi menjadi satu kolom teks untuk mempermudah pemrosesan lebih lanjut."""

!pip install tqdm
from tqdm import tqdm
tqdm.pandas()

from functools import lru_cache

# Stemmer & stopwords dari sebelumnya
stop_factory = StopWordRemoverFactory()
stopwords = set(stop_factory.get_stop_words())  # pakai set agar lookup cepat

stem_factory = StemmerFactory()
stemmer = stem_factory.create_stemmer()

@lru_cache(maxsize=10000)
def cached_stem(word):
    return stemmer.stem(word)

def preprocess_fast(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    words = text.split()
    words = [cached_stem(w) for w in words if w not in stopwords]
    return ' '.join(words)

"""**Insight**:
* @lru_cache mempercepat stemming dengan menyimpan hasil sebelumnya.

* tqdm bantu pantau progres (terutama jika butuh waktu beberapa menit).

* set(stopwords) jauh lebih cepat saat cek keanggotaan dibanding list biasa.
"""

indofakenews_df['clean_text'] = indofakenews_df['teks'].progress_apply(preprocess_fast)

"""# Split Data"""

from sklearn.model_selection import train_test_split

# Split data menjadi data latih (train) dan data uji (test)
X_train_text, X_test_text, y_train, y_test = train_test_split(
    indofakenews_df['clean_text'], indofakenews_df['label'],
    test_size=0.2, stratify=indofakenews_df['label'], random_state=42)

# Lihat jumlah data
print("Jumlah data latih:", len(X_train_text))
print("Jumlah data uji:", len(X_test_text))

"""**Insight**: Membagi data menjadi set pelatihan dan pengujian dengan rasio 80:20, menggunakan stratifikasi untuk menjaga distribusi label.

# Ekstraksi fitur
"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Inisialisasi vectorizer dengan ngram_range=(1, 2) untuk unigram dan bigram
vectorizer = TfidfVectorizer(max_features=1000, ngram_range=(1, 2))

# Fit dan transform data latih, transform data uji
X_train_tfidf = vectorizer.fit_transform(X_train_text)
X_test_tfidf = vectorizer.transform(X_test_text)

"""**Insight**: Menggunakan TF-IDF untuk mengubah teks menjadi fitur numerik, dengan unigram dan bigram untuk menangkap konteks kata.

### Tangani data tidak seimbang dengan SMOTE
"""

from imblearn.over_sampling import SMOTE

# Terapkan SMOTE pada data latih (X_train, y_train)
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_tfidf, y_train)

"""**Insight**: Menggunakan SMOTE untuk menyeimbangkan data pelatihan, agar model tidak bias terhadap kelas mayoritas."""

print("Distribusi kelas setelah SMOTE:")
print(pd.Series(y_train_resampled).value_counts())

"""# Train Model

### Support Vector Machine (SVM)
"""

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Inisialisasi dan latih model SVM pada data latih yang sudah diperbaiki dengan SMOTE
svm_model = SVC(random_state=42)
svm_model.fit(X_train_resampled, y_train_resampled)

# Evaluasi model dengan data uji
y_pred = svm_model.predict(X_test_tfidf)

# Tampilkan hasil evaluasi
print(f"Akurasi: {accuracy_score(y_test, y_pred)}")
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Visualisasi Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
labels = np.unique(y_test)
cm_df = pd.DataFrame(cm, index=labels, columns=labels)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_df, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.title('Confusion Matrix (SVM Tanpa Hyperparameter Tuning)')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

"""**Insight**: Melatih model SVM pada data yang telah diseimbangkan, lalu mengevaluasi performa dengan metrik akurasi, laporan klasifikasi, dan Confusion Matrix."""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Inisialisasi model Random Forest dengan parameter default
rf_model = RandomForestClassifier(random_state=42)

# Latih model pada data latih yang sudah diperbaiki dengan SMOTE
rf_model.fit(X_train_resampled, y_train_resampled)

# Prediksi pada data uji
y_pred_rf = rf_model.predict(X_test_tfidf)

# Tampilkan hasil evaluasi
print(f"Akurasi Random Forest (Tanpa Hyperparameter Tuning): {accuracy_score(y_test, y_pred_rf)}")
print("Classification Report:")
print(classification_report(y_test, y_pred_rf))

# Visualisasi Confusion Matrix
cm = confusion_matrix(y_test, y_pred_rf)
labels = np.unique(y_test)
cm_df = pd.DataFrame(cm, index=labels, columns=labels)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_df, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.title('Confusion Matrix (Random Forest Tanpa Hyperparameter Tuning)')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

"""**Insight**: Melatih model Random Forest sebagai alternatif, lalu membandingkan performanya dengan SVM menggunakan metrik evaluasi yang sama.

# Evaluasi
"""

from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
# Inisialisasi model Random Forest
rf = RandomForestClassifier(random_state=42, class_weight='balanced')

# Definisikan grid parameter untuk RandomizedSearch
param_dist = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']
}

# Setup RandomizedSearchCV
random_search = RandomizedSearchCV(estimator=rf, param_distributions=param_dist, n_iter=10, cv=5, scoring='accuracy', n_jobs=-1)

# Fit model dengan cross-validation
random_search.fit(X_train_resampled, y_train_resampled)

# Output hasil terbaik
print("Best Parameters (Randomized Search):", random_search.best_params_)
print("Best Cross-validation Score:", random_search.best_score_)

# Evaluasi model terbaik
y_pred_random = random_search.best_estimator_.predict(X_test_tfidf)
print("Akurasi dengan RandomizedSearch: ", accuracy_score(y_test, y_pred_random))

# Tampilkan hasil evaluasi
print(f"Akurasi dengan RandomizedSearch: {accuracy_score(y_test, y_pred_random)}")
print("Classification Report:")
print(classification_report(y_test, y_pred_random))

# Asumsi y_test dan y_pred_random sudah ada dari kode sebelumnya
# Membuat Confusion Matrix
cm = confusion_matrix(y_test, y_pred_random)

# Mendapatkan label kelas (misalnya, jika y_test berupa kategori biner atau multiclass)
labels = np.unique(y_test)

# Membuat DataFrame untuk visualisasi
cm_df = pd.DataFrame(cm, index=labels, columns=labels)

# Visualisasi Confusion Matrix dengan heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(cm_df, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

"""**Insight**: Mengoptimalkan model Random Forest dengan RandomizedSearchCV untuk menemukan hyperparameter terbaik, lalu mengevaluasi performanya."""

from sklearn.svm import SVC
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

# Inisialisasi model SVM
svm_model = SVC(random_state=42)

# Definisikan grid parameter untuk RandomizedSearch
param_dist = {
    'C': [0.1, 1, 10, 100],  # Nilai C untuk regularisasi
    'kernel': ['linear', 'rbf', 'poly'],  # Jenis kernel
    'gamma': ['scale', 'auto', 0.001, 0.01, 0.1, 1],  # Nilai gamma untuk kernel rbf/poly
    'degree': [2, 3, 4],  # Derajat polinomial (hanya berlaku untuk kernel 'poly')
}

# Setup RandomizedSearchCV
random_search_svm = RandomizedSearchCV(
    estimator=svm_model,
    param_distributions=param_dist,
    n_iter=10,  # Jumlah kombinasi yang akan dicoba
    cv=5,  # 5-fold cross-validation
    scoring='accuracy',  # Metrik evaluasi
    n_jobs=-1,  # Gunakan semua CPU untuk mempercepat
    random_state=42
)

# Fit model dengan cross-validation pada data yang sudah diperbaiki dengan SMOTE
random_search_svm.fit(X_train_resampled, y_train_resampled)

# Output hasil terbaik
print("Best Parameters (Randomized Search untuk SVM):", random_search_svm.best_params_)
print("Best Cross-validation Score:", random_search_svm.best_score_)

# Evaluasi model terbaik pada data uji
y_pred_svm = random_search_svm.best_estimator_.predict(X_test_tfidf)

# Tampilkan hasil evaluasi
print(f"Akurasi dengan RandomizedSearch: {accuracy_score(y_test, y_pred_svm)}")
print("Classification Report:")
print(classification_report(y_test, y_pred_svm))

# Visualisasi Confusion Matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred_svm)
labels = np.unique(y_test)
cm_df = pd.DataFrame(cm, index=labels, columns=labels)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_df, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.title('Confusion Matrix (SVM dengan RandomizedSearch)')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

"""**Insight**: Mengoptimalkan model SVM dengan RandomizedSearchCV untuk meningkatkan performa, lalu mengevaluasi hasilnya dengan metrik yang sama."""